[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb -q"
# runner = "probe-rs run --chip STM32F401CCUx"
runner = [ "probe-rs", "run", "--chip", "STM32F401CCUx", "--log-format", "{t} [{m}] {f}:{l} {L} {s:severity}" ]

[build]
target = "thumbv7em-none-eabihf"    # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "info"
